"""empty message

Revision ID: 40ab670e4498
Revises: cef904ed6776
Create Date: 2022-03-02 22:48:45.543100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40ab670e4498'
down_revision = 'cef904ed6776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['Budget.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Budget', sa.Column('title', sa.Float(), nullable=False))
    op.drop_constraint('Budget_currency_id_fkey', 'Budget', type_='foreignkey')
    op.drop_column('Budget', 'description')
    op.drop_column('Budget', 'activity_description')
    op.drop_column('Budget', 'currency_id')
    op.drop_column('Budget', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Budget', sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Budget', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Budget', sa.Column('activity_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Budget', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('Budget_currency_id_fkey', 'Budget', 'currency', ['currency_id'], ['id'])
    op.drop_column('Budget', 'title')
    op.drop_table('budget_details')
    # ### end Alembic commands ###
