"""empty message

Revision ID: 48ed34c404c0
Revises: 40ab670e4498
Create Date: 2022-03-02 22:59:02.846914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48ed34c404c0'
down_revision = '40ab670e4498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Budget', sa.Column('name', sa.Text(), nullable=False))
    op.drop_column('Budget', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Budget', sa.Column('title', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('Budget', 'name')
    # ### end Alembic commands ###
