"""empty message

Revision ID: 52f09e8f61ec
Revises: da91367a8ef2
Create Date: 2022-02-11 08:33:46.024172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f09e8f61ec'
down_revision = 'da91367a8ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'updated_at')
    # ### end Alembic commands ###
