"""empty message

Revision ID: 689786c3f73e
Revises: 48ed34c404c0
Create Date: 2022-03-03 02:42:58.269500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689786c3f73e'
down_revision = '48ed34c404c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depts', sa.Column('borrower_name', sa.Text(), nullable=True))
    op.drop_column('depts', 'destination')
    op.alter_column('savings', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('depts', sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('depts', 'borrower_name')
    # ### end Alembic commands ###
