"""empty message

Revision ID: c3b3be67f435
Revises: 52f09e8f61ec
Create Date: 2022-02-13 06:21:16.463965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b3be67f435'
down_revision = '52f09e8f61ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('depts', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('expense', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('expense', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'currency', ['currency_id'], ['id'])
    op.alter_column('loans', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'currency_id')
    op.drop_column('expense', 'title')
    op.alter_column('depts', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
