"""empty message

Revision ID: cef904ed6776
Revises: c3b3be67f435
Create Date: 2022-03-02 22:40:27.777243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef904ed6776'
down_revision = 'c3b3be67f435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Budget', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('Budget', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.alter_column('Budget', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Budget', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Budget', 'end_date')
    op.drop_column('Budget', 'start_date')
    # ### end Alembic commands ###
