"""empty message

Revision ID: da91367a8ef2
Revises: 3fc18f7d31ed
Create Date: 2022-02-11 01:22:11.612431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da91367a8ef2'
down_revision = '3fc18f7d31ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'gender',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'gender',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
