# pull official base image
FROM python:3.9.5-slim-buster

# Work directory
WORKDIR /usr/src/app

# Environment variables
# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1


# Install dependencies
RUN python3 -m pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN python3 -m pip install -r requirements.txt 
RUN python3 -m pip install python-dotenv


# Install system depencies
RUN apt-get update && \ 
    apt-get install -y netcat 

# curl \
# openssh-server

# ADD ./.profile.d /app/.profile.d
# RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# RUN echo "healthy" >> /tmp/healthy && \
#     cat /tmp/healthy

# ENV FLASK_ENV=development

# Copy project
COPY . /usr/src/app/

# Run entrypoint.sh && alow the privilage to the roote
USER root
RUN chmod +x /usr/src/app/entrypoint.dev.sh
# ENTRYPOINT ["sh", "/usr/src/app/entrypoint.dev.sh"]
CMD [ "/usr/src/app/entrypoint.dev.sh" ]
