"""empty message

Revision ID: 0f7366870bf6
Revises: 5437f84dc937
Create Date: 2022-05-14 10:56:19.151628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7366870bf6'
down_revision = '5437f84dc937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessor_landlord_to_rent_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lessor_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_status'], ['request_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accommodation', sa.Column('rent_payment_id', sa.Integer(), nullable=False))
    op.drop_constraint('accommodation_lessor_id_fkey', 'accommodation', type_='foreignkey')
    op.drop_constraint('accommodation_landlord_id_fkey', 'accommodation', type_='foreignkey')
    op.create_foreign_key(None, 'accommodation', 'lessor_landlord_to_rent_payment', ['rent_payment_id'], ['id'])
    op.drop_column('accommodation', 'lessor_id')
    op.drop_column('accommodation', 'landlord_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('landlord_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('accommodation', sa.Column('lessor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accommodation', type_='foreignkey')
    op.create_foreign_key('accommodation_landlord_id_fkey', 'accommodation', 'users', ['landlord_id'], ['id'])
    op.create_foreign_key('accommodation_lessor_id_fkey', 'accommodation', 'users', ['lessor_id'], ['id'])
    op.drop_column('accommodation', 'rent_payment_id')
    op.drop_table('lessor_landlord_to_rent_payment')
    # ### end Alembic commands ###
