"""empty message

Revision ID: 29805e6bbce4
Revises: 5d80887deac5
Create Date: 2022-09-08 07:14:47.412370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29805e6bbce4'
down_revision = '5d80887deac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loans', 'budget_details', ['budget_detail_id'], ['id'])
    op.create_foreign_key(None, 'loans', 'budget_option', ['budget_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'budget_option_id')
    op.drop_column('loans', 'budget_detail_id')
    # ### end Alembic commands ###
