"""empty message

Revision ID: 374dd4626bc2
Revises: 5b829da0d60a
Create Date: 2022-09-02 06:58:14.218289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374dd4626bc2'
down_revision = '5b829da0d60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('group_members', sa.Column('member_id', sa.Integer(), nullable=False))
    op.drop_constraint('group_members_user_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['member_id'], ['id'])
    op.create_foreign_key(None, 'group_members', 'users', ['sender_id'], ['id'])
    op.drop_column('group_members', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_user_id_fkey', 'group_members', 'users', ['user_id'], ['id'])
    op.drop_column('group_members', 'member_id')
    op.drop_column('group_members', 'sender_id')
    # ### end Alembic commands ###
