"""empty message

Revision ID: 5437f84dc937
Revises: 25146edfffe4
Create Date: 2022-05-13 23:04:52.618174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5437f84dc937'
down_revision = '25146edfffe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Budget', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('accommodation', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.add_column('accommodation', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accommodation', 'budget_categories', ['budget_category_id'], ['id'])
    op.create_foreign_key(None, 'accommodation', 'budget_option', ['budget_option_id'], ['id'])
    op.add_column('budget_details', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.add_column('budget_details', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.add_column('budget_details', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('budget_details', sa.Column('budget_amount', sa.Float(), nullable=True))
    op.add_column('budget_details', sa.Column('actual_amount', sa.Float(), nullable=True))
    op.add_column('budget_details', sa.Column('difference_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'budget_details', 'budget_categories', ['budget_category_id'], ['id'])
    op.create_foreign_key(None, 'budget_details', 'budget_option', ['budget_option_id'], ['id'])
    op.drop_column('budget_details', 'activity_description')
    op.drop_column('budget_details', 'amount')
    op.drop_column('budget_details', 'description')
    op.add_column('dept_note_book', sa.Column('memeber_id', sa.Integer(), nullable=True))
    op.add_column('dept_note_book', sa.Column('notebook_id', sa.Integer(), nullable=True))
    op.drop_constraint('dept_note_book_friend_id_fkey', 'dept_note_book', type_='foreignkey')
    op.create_foreign_key(None, 'dept_note_book', 'notebook_member', ['memeber_id'], ['id'])
    op.create_foreign_key(None, 'dept_note_book', 'notebook', ['notebook_id'], ['id'])
    op.drop_column('dept_note_book', 'friend_id')
    op.add_column('dept_payment', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.add_column('dept_payment', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dept_payment', 'budget_categories', ['budget_category_id'], ['id'])
    op.create_foreign_key(None, 'dept_payment', 'budget_option', ['budget_option_id'], ['id'])
    op.add_column('expense_details', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.add_column('expense_details', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense_details', 'budget_categories', ['budget_category_id'], ['id'])
    op.create_foreign_key(None, 'expense_details', 'budget_option', ['budget_option_id'], ['id'])
    op.add_column('loan_payment', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.add_column('loan_payment', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan_payment', 'budget_categories', ['budget_category_id'], ['id'])
    op.create_foreign_key(None, 'loan_payment', 'budget_option', ['budget_option_id'], ['id'])
    op.add_column('savings', sa.Column('budget_category_id', sa.Integer(), nullable=True))
    op.add_column('savings', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'savings', 'budget_option', ['budget_option_id'], ['id'])
    op.create_foreign_key(None, 'savings', 'budget_categories', ['budget_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings', type_='foreignkey')
    op.drop_constraint(None, 'savings', type_='foreignkey')
    op.drop_column('savings', 'budget_option_id')
    op.drop_column('savings', 'budget_category_id')
    op.drop_constraint(None, 'loan_payment', type_='foreignkey')
    op.drop_constraint(None, 'loan_payment', type_='foreignkey')
    op.drop_column('loan_payment', 'budget_option_id')
    op.drop_column('loan_payment', 'budget_category_id')
    op.drop_constraint(None, 'expense_details', type_='foreignkey')
    op.drop_constraint(None, 'expense_details', type_='foreignkey')
    op.drop_column('expense_details', 'budget_option_id')
    op.drop_column('expense_details', 'budget_category_id')
    op.drop_constraint(None, 'dept_payment', type_='foreignkey')
    op.drop_constraint(None, 'dept_payment', type_='foreignkey')
    op.drop_column('dept_payment', 'budget_option_id')
    op.drop_column('dept_payment', 'budget_category_id')
    op.add_column('dept_note_book', sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dept_note_book', type_='foreignkey')
    op.drop_constraint(None, 'dept_note_book', type_='foreignkey')
    op.create_foreign_key('dept_note_book_friend_id_fkey', 'dept_note_book', 'notebook_member', ['friend_id'], ['id'])
    op.drop_column('dept_note_book', 'notebook_id')
    op.drop_column('dept_note_book', 'memeber_id')
    op.add_column('budget_details', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('budget_details', sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('budget_details', sa.Column('activity_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'budget_details', type_='foreignkey')
    op.drop_constraint(None, 'budget_details', type_='foreignkey')
    op.drop_column('budget_details', 'difference_amount')
    op.drop_column('budget_details', 'actual_amount')
    op.drop_column('budget_details', 'budget_amount')
    op.drop_column('budget_details', 'summary')
    op.drop_column('budget_details', 'budget_category_id')
    op.drop_column('budget_details', 'budget_option_id')
    op.drop_constraint(None, 'accommodation', type_='foreignkey')
    op.drop_constraint(None, 'accommodation', type_='foreignkey')
    op.drop_column('accommodation', 'budget_option_id')
    op.drop_column('accommodation', 'budget_category_id')
    op.drop_column('Budget', 'description')
    op.drop_table('budget_option')
    op.drop_table('budget_categories')
    # ### end Alembic commands ###
