"""empty message

Revision ID: 5a242f034452
Revises: 92be516c7592
Create Date: 2022-05-10 09:16:38.629978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a242f034452'
down_revision = '92be516c7592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_note_book', sa.Column('notebook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan_note_book', 'notebook', ['notebook_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan_note_book', type_='foreignkey')
    op.drop_column('loan_note_book', 'notebook_id')
    # ### end Alembic commands ###
