"""empty message

Revision ID: 5b829da0d60a
Revises: dc30109a7eb0
Create Date: 2022-08-28 13:35:12.304640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b829da0d60a'
down_revision = 'dc30109a7eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_depts', sa.Column('contribution_id', sa.Integer(), nullable=True))
    op.add_column('group_depts', sa.Column('contributor', sa.Boolean(), nullable=True))
    op.drop_constraint('group_depts_currency_id_fkey', 'group_depts', type_='foreignkey')
    op.create_foreign_key(None, 'group_depts', 'group_manage_money', ['contribution_id'], ['id'])
    op.drop_column('group_depts', 'amount')
    op.drop_column('group_depts', 'description')
    op.drop_column('group_depts', 'currency_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_depts', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('group_depts', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('group_depts', sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group_depts', type_='foreignkey')
    op.create_foreign_key('group_depts_currency_id_fkey', 'group_depts', 'currency', ['currency_id'], ['id'])
    op.drop_column('group_depts', 'contributor')
    op.drop_column('group_depts', 'contribution_id')
    # ### end Alembic commands ###
