"""empty message

Revision ID: 5d80887deac5
Revises: 9292c52a61d5
Create Date: 2022-09-08 06:48:59.131117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d80887deac5'
down_revision = '9292c52a61d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('accommodation_budget_category_id_fkey', 'accommodation', type_='foreignkey')
    op.create_foreign_key(None, 'accommodation', 'budget_details', ['budget_detail_id'], ['id'])
    op.drop_column('accommodation', 'budget_category_id')
    op.drop_constraint('budget_details_budget_option_id_fkey', 'budget_details', type_='foreignkey')
    op.drop_column('budget_details', 'budget_option_id')
    op.add_column('dept_payment', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('dept_payment_budget_category_id_fkey', 'dept_payment', type_='foreignkey')
    op.create_foreign_key(None, 'dept_payment', 'budget_details', ['budget_detail_id'], ['id'])
    op.drop_column('dept_payment', 'budget_category_id')
    op.add_column('expense_details', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('expense_details_budget_category_id_fkey', 'expense_details', type_='foreignkey')
    op.create_foreign_key(None, 'expense_details', 'budget_details', ['budget_detail_id'], ['id'])
    op.drop_column('expense_details', 'budget_category_id')
    op.add_column('group_depts', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.add_column('group_depts', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group_depts', 'budget_details', ['budget_detail_id'], ['id'])
    op.create_foreign_key(None, 'group_depts', 'budget_option', ['budget_option_id'], ['id'])
    op.add_column('group_manage_money', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.add_column('group_manage_money', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group_manage_money', 'budget_option', ['budget_option_id'], ['id'])
    op.create_foreign_key(None, 'group_manage_money', 'budget_details', ['budget_detail_id'], ['id'])
    op.add_column('loan_payment', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('loan_payment_budget_category_id_fkey', 'loan_payment', type_='foreignkey')
    op.create_foreign_key(None, 'loan_payment', 'budget_details', ['budget_detail_id'], ['id'])
    op.drop_column('loan_payment', 'budget_category_id')
    op.add_column('record_dept_payment', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('record_dept_payment_budget_category_id_fkey', 'record_dept_payment', type_='foreignkey')
    op.create_foreign_key(None, 'record_dept_payment', 'budget_details', ['budget_detail_id'], ['id'])
    op.drop_column('record_dept_payment', 'budget_category_id')
    op.add_column('savings', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('savings_budget_category_id_fkey', 'savings', type_='foreignkey')
    op.create_foreign_key(None, 'savings', 'budget_details', ['budget_detail_id'], ['id'])
    op.drop_column('savings', 'budget_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('budget_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'savings', type_='foreignkey')
    op.create_foreign_key('savings_budget_category_id_fkey', 'savings', 'budget_categories', ['budget_category_id'], ['id'])
    op.drop_column('savings', 'budget_detail_id')
    op.add_column('record_dept_payment', sa.Column('budget_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record_dept_payment', type_='foreignkey')
    op.create_foreign_key('record_dept_payment_budget_category_id_fkey', 'record_dept_payment', 'budget_categories', ['budget_category_id'], ['id'])
    op.drop_column('record_dept_payment', 'budget_detail_id')
    op.add_column('loan_payment', sa.Column('budget_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loan_payment', type_='foreignkey')
    op.create_foreign_key('loan_payment_budget_category_id_fkey', 'loan_payment', 'budget_categories', ['budget_category_id'], ['id'])
    op.drop_column('loan_payment', 'budget_detail_id')
    op.drop_constraint(None, 'group_manage_money', type_='foreignkey')
    op.drop_constraint(None, 'group_manage_money', type_='foreignkey')
    op.drop_column('group_manage_money', 'budget_option_id')
    op.drop_column('group_manage_money', 'budget_detail_id')
    op.drop_constraint(None, 'group_depts', type_='foreignkey')
    op.drop_constraint(None, 'group_depts', type_='foreignkey')
    op.drop_column('group_depts', 'budget_option_id')
    op.drop_column('group_depts', 'budget_detail_id')
    op.add_column('expense_details', sa.Column('budget_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expense_details', type_='foreignkey')
    op.create_foreign_key('expense_details_budget_category_id_fkey', 'expense_details', 'budget_categories', ['budget_category_id'], ['id'])
    op.drop_column('expense_details', 'budget_detail_id')
    op.add_column('dept_payment', sa.Column('budget_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dept_payment', type_='foreignkey')
    op.create_foreign_key('dept_payment_budget_category_id_fkey', 'dept_payment', 'budget_categories', ['budget_category_id'], ['id'])
    op.drop_column('dept_payment', 'budget_detail_id')
    op.add_column('budget_details', sa.Column('budget_option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('budget_details_budget_option_id_fkey', 'budget_details', 'budget_option', ['budget_option_id'], ['id'])
    op.add_column('accommodation', sa.Column('budget_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accommodation', type_='foreignkey')
    op.create_foreign_key('accommodation_budget_category_id_fkey', 'accommodation', 'budget_categories', ['budget_category_id'], ['id'])
    op.drop_column('accommodation', 'budget_detail_id')
    # ### end Alembic commands ###
