"""empty message

Revision ID: 5e5201b4453a
Revises: e47420fe6690
Create Date: 2022-07-08 23:09:39.005224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5201b4453a'
down_revision = 'e47420fe6690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('period_range', sa.Text(), nullable=True))
    op.add_column('accommodation', sa.Column('month_name', sa.Text(), nullable=True))
    op.add_column('accommodation', sa.Column('year', sa.Text(), nullable=True))
    op.drop_column('accommodation', 'periode_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('periode_range', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('accommodation', 'year')
    op.drop_column('accommodation', 'month_name')
    op.drop_column('accommodation', 'period_range')
    # ### end Alembic commands ###
