"""empty message

Revision ID: 8504ca66be06
Revises: 29805e6bbce4
Create Date: 2022-09-08 07:29:29.091382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8504ca66be06'
down_revision = '29805e6bbce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depts', sa.Column('budget_detail_id', sa.Integer(), nullable=True))
    op.add_column('depts', sa.Column('budget_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'depts', 'budget_option', ['budget_option_id'], ['id'])
    op.create_foreign_key(None, 'depts', 'budget_details', ['budget_detail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'depts', type_='foreignkey')
    op.drop_constraint(None, 'depts', type_='foreignkey')
    op.drop_column('depts', 'budget_option_id')
    op.drop_column('depts', 'budget_detail_id')
    # ### end Alembic commands ###
