"""empty message

Revision ID: 8813fa88f9cb
Revises: 9477fc0e5476
Create Date: 2022-10-18 19:29:12.028791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8813fa88f9cb'
down_revision = '9477fc0e5476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_default_currency', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_default_currency', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_default_currency', 'updated_at')
    op.drop_column('user_default_currency', 'created_at')
    # ### end Alembic commands ###
