"""empty message

Revision ID: 9292c52a61d5
Revises: 374dd4626bc2
Create Date: 2022-09-02 07:21:10.194563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9292c52a61d5'
down_revision = '374dd4626bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('group_members', sa.Column('member_id', sa.Integer(), nullable=True))
    op.add_column('group_members', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('group_members_user_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['member_id'], ['id'])
    op.create_foreign_key(None, 'group_members', 'users', ['sender_id'], ['id'])
    op.drop_column('group_members', 'user_id')
    op.drop_column('group_members', 'requested_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('group_members', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_user_id_fkey', 'group_members', 'users', ['user_id'], ['id'])
    op.drop_column('group_members', 'sent_at')
    op.drop_column('group_members', 'member_id')
    op.drop_column('group_members', 'sender_id')
    # ### end Alembic commands ###
