"""empty message

Revision ID: a2cd1f76634a
Revises: 5e5201b4453a
Create Date: 2022-08-08 20:55:33.679723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cd1f76634a'
down_revision = '5e5201b4453a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_dept_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('budget_category_id', sa.Integer(), nullable=True),
    sa.Column('budget_option_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['budget_option_id'], ['budget_option.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['dept_note_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('group_depts', sa.Column('member_id', sa.Integer(), nullable=True))
    op.drop_constraint('group_depts_memeber_id_fkey', 'group_depts', type_='foreignkey')
    op.create_foreign_key(None, 'group_depts', 'group_members', ['member_id'], ['id'])
    op.drop_column('group_depts', 'memeber_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_depts', sa.Column('memeber_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_depts', type_='foreignkey')
    op.create_foreign_key('group_depts_memeber_id_fkey', 'group_depts', 'group_members', ['memeber_id'], ['id'])
    op.drop_column('group_depts', 'member_id')
    op.drop_table('record_dept_payment')
    # ### end Alembic commands ###
