"""empty message

Revision ID: c258dc026978
Revises: 5a242f034452
Create Date: 2022-05-10 13:17:04.951429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c258dc026978'
down_revision = '5a242f034452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('code', sa.String(length=10), nullable=False))
    op.add_column('currency', sa.Column('description', sa.String(length=200), nullable=True))
    op.drop_column('currency', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('currency', 'description')
    op.drop_column('currency', 'code')
    # ### end Alembic commands ###
